title: RJuall's GitHub Pages
description: Convenient Web Hosting is Convenient
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: /rjuall
url: https://rjuall.github.io

defaults:
  -
    scope:
      type: haskell
      path: _haskell
    values:
      is_haskell: true
      layout: haskell