title: RJuall's GitHub Pages
description: Convenient Web Hosting is Convenient
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
baseurl: /rjuall
url: https://rjuall.github.io

collections:
  haskell:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      type: haskell
      path: _haskell
    values:
      is_haskell: true
      layout: default