title: RJuall's GitHub Pages
description: Convenient Web Hosting is Convenient
markdown: kramdown
theme: jekyll-theme-slate
baseurl: /rjuall
url: https://rjuall.github.io

defaults:
  -
    scope:
      type: haskell
      path: _haskell
    values:
      is_haskell: true
      layout: haskell