markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

source: .
collections_dir: ./collections
layouts_dir: _layouts
inclueds_dir: _includes

collections:
  posts:
    output: true
