markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

collections:
  haskell:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      type: haskell
      path: _haskell
    values:
      is_haskell: true
      layout: default